# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logsum <- function(y) {
    .Call(`_HMMARM_logsum`, y)
}

lAlphaBetaGamma <- function(lemission, A, Pi) {
    .Call(`_HMMARM_lAlphaBetaGamma`, lemission, A, Pi)
}

AlphaBetaGamma_scaled <- function(emission, A, Pi) {
    .Call(`_HMMARM_AlphaBetaGamma_scaled`, emission, A, Pi)
}

Viterbi <- function(A, Pi, emission) {
    .Call(`_HMMARM_Viterbi`, A, Pi, emission)
}

UpdateTheta <- function(yt, logpi, logA, D, CD, C, phi, mu, theta) {
    .Call(`_HMMARM_UpdateTheta`, yt, logpi, logA, D, CD, C, phi, mu, theta)
}

UpdateMu <- function(yt, D, C, CD, phi, theta) {
    .Call(`_HMMARM_UpdateMu`, yt, D, C, CD, phi, theta)
}

UpdateS2r <- function(yt, D, CD, C, phi, mu, theta) {
    .Call(`_HMMARM_UpdateS2r`, yt, D, CD, C, phi, mu, theta)
}

l1 <- function(phi, y, x, D, CD, s2r, mu, theta) {
    .Call(`_HMMARM_l1`, phi, y, x, D, CD, s2r, mu, theta)
}

l2 <- function(logpi, logA, S) {
    .Call(`_HMMARM_l2`, logpi, logA, S)
}

rcpp_hello_world <- function() {
    .Call(`_HMMARM_rcpp_hello_world`)
}

